# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userfollowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowers',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userfollowers',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
    ]
